app:
  port: 5050

paths:
  photo_dir: /photos
  cache_dir: /cache
  photo_cache_dir: /cache/photos
  log_dir: /logs

cache:
  limit_enabled: false
  limit: 2000
  same_day_cycle: 100
image:
  max_width: 2080
  max_height: 768
